---
# tasks file for balancer
- name:
  package:
    name: haproxy
    state: present
- name:
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restarted  load balancer
- name: load balancer
  service:
    name: haproxy
    state: started
    enabled: yes
